[phases.setup]
nixPkgs = ["python311", "gcc", "git-lfs"]

[phases.install]
cmds = ["git lfs install", "git lfs pull", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120"
